on:
  workflow_dispatch:

name: MacOSX11 Test 

jobs:

  mac-test:

    runs-on: macos-11

    steps:

      - name: Checkout Repository
        uses: actions/checkout@3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'devel'

      - name: Install BiocManager
        run: install.packages("BiocManager", repos="https://cran.r-project.org")
        shell: Rscript {0}

      - name: Install packages 
        run: |
          setwd($GITHUB_WORKSPACE)
          install.packages("fgsea_1.25.2.tgz", type="binary", repos=NULL)
        shell: Rscript {0}

      - name: Test Case
        run: |
          library("fgsea")
        shell: Rscript {0}
