on:
  workflow_dispatch:

name: MacOSX11 Test 

jobs:

  mac-test:

    runs-on: macos-12

    steps:

      - name: Configure git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Install SaltStack
        run: |
          echo "Set up SaltStack"
          echo "Download Salt"
          curl -LO https://repo.saltproject.io/salt/py3/macos/latest/salt-3006.6-py3-x86_64.pkg
          echo "Install Salt"
          sudo installer -verbose -pkg salt-3006.6-py3-x86_64.pkg -target /

      - name: Clone Bioconductor/bioconductor_salt
        uses: actions/checkout@v4
        with:
          repository: Bioconductor/bioconductor_salt
          ref: issue/141

      - name: Copy Salt files
        run: |
          echo "Copy Salt files"
          sudo cp bioconductor_salt/minion.d/mac.minion.conf /etc/salt/minion
          sudo cp -R bioconductor_salt/saltstack /opt
          sudo cp init.sls /opt/saltstack/pillar/custom

      - name: Inefficiently make custom file
        run: |
          sudo echo "{% set branch = 'devel' %}" >> /opt/saltstack/pillar/custom/init.sls
          sudo echo "{% set version = '3.19' %}" >> /opt/saltstack/pillar/custom/init.sls
          sudo echo "{% set environment = 'dev' %}" >> /opt/saltstack/pillar/custom/init.sls
          sudo echo "{% set cycle = 'patch' %}" >> /opt/saltstack/pillar/custom/init.sls
          sudo echo "{% set name = 'bbs-machine' %}" >> /opt/saltstack/pillar/custom/init.sls
          sudo echo "{% set immunespace_pwd = '' %}" >> /opt/saltstack/pillar/custom/init.sls
          sudo echo "{% set machine_type = 'standalone' %}" >> /opt/saltstack/pillar/custom/init.sls

      - name: Run Salt
        run: |
          echo "Run Salt"
          sudo salt-call --local state.highstate -l debug
