on:
  workflow_dispatch:

name: MacOSX11 Test 

jobs:

  mac-test:

    runs-on: macos-11

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'alpha'

      - name: Install BiocManager and Dependencies
        run: |
          install.packages("BiocManager", repos="https://cran.r-project.org")
          pkgs <- c("BiocParallel", "Rcpp", "data.table", "stats", "ggplot2",
                    "cowplot", "grid", "fastmatch", "Matrix", "scales",
                    "utils")
          repos <- c(BiocManager::repositories(), "https://cran.r-project.org")
          BiocManager::install(pkgs)
          install.packages(pkgs, repos=repos)
        shell: Rscript {0}

      - name: Install packages 
        run: |
          cd $GITHUB_WORKSPACE
          Rscript -e "install.packages('fgsea_1.25.2.tgz', type='binary', repos=NULL)"

      - name: Test Case
        run: |
          library("fgsea")
        shell: Rscript {0}
