on:
  workflow_dispatch:

name: MacOSX11 Test 

jobs:

  mac-test:

    runs-on: macos-11

    steps:

      - name: Install SaltStack
        run: |
          echo "Set up SaltStack"
          echo "Download Salt"
          curl -LO https://repo.saltproject.io/salt/py3/macos/latest/salt-3006.6-py3-x86_64.pkg
          echo "Install Salt"
          sudo installer -verbose -pkg salt-3006.6-py3-x86_64.pkg -target /

      - name: Clone jwokaty/bioconductor_salt
        uses: actions/checkout@v4
        with:
          repository: jwokaty/bioconductor_salt
          ref: issue/141

      - name: Copy Salt files
        run: |
          echo "Copy Salt files"
          ls -lar
          sudo cp $GITHUB_WORKSPACE/saltstack/minion.d/mac.minion.conf /etc/salt/minion
          sudo cp -R $GITHUB_WORKSPACE/saltstack /opt

      - name: Inefficiently make custom file
        run: |
          echo "{% set branch = 'devel' %}" >> init.sls
          echo "{% set version = '3.19' %}" >> init.sls
          echo "{% set environment = 'dev' %}" >> init.sls
          echo "{% set cycle = 'patch' %}" >> init.sls
          echo "{% set name = 'bbs-machine' %}" >> init.sls
          echo "{% set immunespace_pwd = '' %}" >> init.sls
          echo "{% set machine_type = 'standalone' %}" >> init.sls
          sudo mv init.sls /opt/saltstack/pillar/custom

      - name: Run Salt
        run: |
          echo "Run Salt"
          sudo salt-call --local state.highstate -l debug
