on:
  workflow_dispatch:

name: MacOSX11 Test 

jobs:

  mac-test:

    runs-on: macos-11

    steps:

      - name: Install XQuartz - Can I use installer?
        run: |
          curl -LO https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.5/XQuartz-2.8.5.pkg
          sudo installer -pkg XQuartz-2.8.5.pkg -target /
  
      - name: Install gfortran
        run: |
          curl -LO https://github.com/R-macos/gcc-12-branch/releases/download/12.2-darwin-r0/gfortran-12.2-darwin20-r0-universal.tar.xz
          sudo tar -xf gfortran-12.2-darwin20-r0-universal.tar.xz -C /

      - name: Export gfortran path
        run: |
          export PATH=$PATH:/opt/gfortran/bin
          which gfortran
